site_name: Tecnologías Web
site_description: Tecnologías Web. Asignatura del Grado en Ingeniería y Sistemas de Datos. ETSIT-UPM
docs_dir: docs
site_dir: html
theme: readthedocs
extra_css: [extra.css, _images/introduccion/entornos.png]
static_dir: docs/_images
use_directory_urls: false
nav:
  - Tecnología Web: 'index.md'
  - Introduccion: 
    - Evolución de la web: 'introduccion/evolucion.md'
    - Cliente/Servidor: 'introduccion/client_server.md'
    - Desarrollo Web: 'introduccion/desarrollo_web.md'
  - Tema 1:
    - 'tema1/introduccion.md'
    - HTML: 'tema1/html.md'
    - CSS: 'tema1/css.md'
  - Tema 2:
    - Servidores: 'tema2/servidores.md'
    - Flask: 'tema2/flask.md'
    - URL: 'tema2/url.md'
    - MVC: 'tema2/mvc.md'
    - Templates: 'tema2/jinja2.md'
    - Blueprints: 'tema2/blueprints.md'
    - HTTP: 'tema2/http.md'
    - Middlewares: 'tema2/middlewares.md'
  - Tema 3:
    - Descarga de ficheros: 'tema3/files.md'
    - Ficheros públicos: 'tema3/public.md'
    - Ficheros privados: 'tema3/private.md'
  - Tema 4:
    - Modelado de datos: 'tema4/orm.md'
    - Modelos y migraciones: 'tema4/modelos-migraciones.md'
    - Seeders: 'tema4/seeders.md'
    - Queries: 'tema4/consultas.md'
  - Tema 5:
    - Seguridad: 'tema5/seguridad.md'
    - HTTPs: 'tema5/https.md'
    - Autenticacion: 'tema5/autenticacion.md'
    - Autorización: 'tema5/autorizacion.md'
#  - Tema 6:
#    - Javascript: 'tema6/javascript.md'
#    - Single Page Application: 'tema6/spa.md'
  - Tema 7:
    - Emails: 'tema7/email.md'
    - Websockets: 'tema7/websockets.md'
    - Logging: 'tema7/logging.md'
    - Caché: 'tema7/cache.md'
